version: '3.7'

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        environment:
            XDEBUG_CONFIG: client_host=${REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=voting
        volumes:
            - .:/app
        working_dir: /app
        links:
            - mysql

    nginx:
        build:
          context: .
          dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - .:/app
        ports:
            - 80:80
        links:
            - php

    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root_dev
            MYSQL_DATABASE: voting_dev
        ports:
            - 3306:3306
        volumes:
            - mysql-data-voting:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql-data-voting:
