openapi: 3.0.1

info:
  version: 0.0.1
  title: "Voting Api"

paths:
  /:
    get:
      summary: "Get Lumen version"
      responses:
        200:
          description: "Version of Lumen"
          content:
            text/plain:
              schema:
                type: string
