openapi: 3.0.1
# see https://api.vote.dowith.me/swagger/vote-1.0.yml

info:
  version: 0.0.1
  title: "Voting Api"

paths:
  /polls:
    get:
      summary: "Get "
      responses:
        422:
          description: "Validation error"
          content:
            application/json:
              schema:
                er

  /:
    get:
      summary: "Get Lumen version"
      responses:
        200:
          description: "Version of Lumen"
          content:
            text/plain:
              schema:
                type: string
